version: '3.8'

services:
  api:
    build: .
    container_name: beed_eeg_api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./mlartifacts:/app/mlartifacts
      - ./mlflow.db:/app/mlflow.db
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  mlflow-ui:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: beed_mlflow_ui
    ports:
      - "5000:5000"
    volumes:
      - ./:/mlflow
    command: mlflow ui --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:////mlflow/mlflow.db --default-artifact-root /mlflow/mlartifacts
    restart: unless-stopped
